package com.github.nicholasmoser.gnt4.seq;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * A class used to read seq execution files generated by the seq execution Lua scripts.
 * See https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/utils/seq_reader_gnt4.lua
 */
public class SeqExecution {
  public static final List<Integer> getOffsets(Path executionPath, Path seqPath) throws IOException {
    String filePath = seqPath.toString().replace("\\", "/");
    List<Integer> offsets = new ArrayList<>();
    List<String> lines = Files.readAllLines(executionPath);
    for (String line : lines) {
      if (line.startsWith("Begin") || line.startsWith("File")) {
        // Ignore headers
        continue;
      }
      String lineFile = line.substring(0, 15);
      if (!filePath.endsWith(lineFile)) {
        // Not a matching file, ignore
        continue;
      }
      String offsetString = line.substring(17, 25);
      offsets.add(Integer.parseInt(offsetString, 16));
    }
    return offsets;
  }
}
