// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: files.proto

package com.github.nicholasmoser;

public final class GNTFileProtos {
  private GNTFileProtos() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface GNTFilesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gntool.GNTFiles)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTFile> getGntFileList();

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    com.github.nicholasmoser.GNTFileProtos.GNTFile getGntFile(int index);

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    int getGntFileCount();

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    java.util.List<? extends com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder> getGntFileOrBuilderList();

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder getGntFileOrBuilder(int index);
  }
  /**
   * Protobuf type {@code gntool.GNTFiles}
   */
  public static final class GNTFiles extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gntool.GNTFiles)
      GNTFilesOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use GNTFiles.newBuilder() to construct.
    private GNTFiles(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private GNTFiles() {
      gntFile_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new GNTFiles();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private GNTFiles(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gntFile_ =
                    new java.util.ArrayList<com.github.nicholasmoser.GNTFileProtos.GNTFile>();
                mutable_bitField0_ |= 0x00000001;
              }
              gntFile_.add(input.readMessage(
                  com.github.nicholasmoser.GNTFileProtos.GNTFile.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gntFile_ = java.util.Collections.unmodifiableList(gntFile_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFiles_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFiles_fieldAccessorTable
          .ensureFieldAccessorsInitialized(com.github.nicholasmoser.GNTFileProtos.GNTFiles.class,
              com.github.nicholasmoser.GNTFileProtos.GNTFiles.Builder.class);
    }

    public static final int GNT_FILE_FIELD_NUMBER = 1;
    private java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTFile> gntFile_;

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    public java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTFile> getGntFileList() {
      return gntFile_;
    }

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    public java.util.List<? extends com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder> getGntFileOrBuilderList() {
      return gntFile_;
    }

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    public int getGntFileCount() {
      return gntFile_.size();
    }

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    public com.github.nicholasmoser.GNTFileProtos.GNTFile getGntFile(int index) {
      return gntFile_.get(index);
    }

    /**
     * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
     */
    public com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder getGntFileOrBuilder(int index) {
      return gntFile_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      for (int i = 0; i < gntFile_.size(); i++) {
        output.writeMessage(1, gntFile_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      for (int i = 0; i < gntFile_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, gntFile_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.github.nicholasmoser.GNTFileProtos.GNTFiles)) {
        return super.equals(obj);
      }
      com.github.nicholasmoser.GNTFileProtos.GNTFiles other =
          (com.github.nicholasmoser.GNTFileProtos.GNTFiles) obj;

      if (!getGntFileList().equals(other.getGntFileList()))
        return false;
      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGntFileCount() > 0) {
        hash = (37 * hash) + GNT_FILE_FIELD_NUMBER;
        hash = (53 * hash) + getGntFileList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.nicholasmoser.GNTFileProtos.GNTFiles prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code gntool.GNTFiles}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gntool.GNTFiles)
        com.github.nicholasmoser.GNTFileProtos.GNTFilesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFiles_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFiles_fieldAccessorTable
            .ensureFieldAccessorsInitialized(com.github.nicholasmoser.GNTFileProtos.GNTFiles.class,
                com.github.nicholasmoser.GNTFileProtos.GNTFiles.Builder.class);
      }

      // Construct using com.github.nicholasmoser.GNTFileProtos.GNTFiles.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getGntFileFieldBuilder();
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (gntFileBuilder_ == null) {
          gntFile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gntFileBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFiles_descriptor;
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTFiles getDefaultInstanceForType() {
        return com.github.nicholasmoser.GNTFileProtos.GNTFiles.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTFiles build() {
        com.github.nicholasmoser.GNTFileProtos.GNTFiles result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTFiles buildPartial() {
        com.github.nicholasmoser.GNTFileProtos.GNTFiles result =
            new com.github.nicholasmoser.GNTFileProtos.GNTFiles(this);
        int from_bitField0_ = bitField0_;
        if (gntFileBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gntFile_ = java.util.Collections.unmodifiableList(gntFile_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gntFile_ = gntFile_;
        } else {
          result.gntFile_ = gntFileBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.nicholasmoser.GNTFileProtos.GNTFiles) {
          return mergeFrom((com.github.nicholasmoser.GNTFileProtos.GNTFiles) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.nicholasmoser.GNTFileProtos.GNTFiles other) {
        if (other == com.github.nicholasmoser.GNTFileProtos.GNTFiles.getDefaultInstance())
          return this;
        if (gntFileBuilder_ == null) {
          if (!other.gntFile_.isEmpty()) {
            if (gntFile_.isEmpty()) {
              gntFile_ = other.gntFile_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGntFileIsMutable();
              gntFile_.addAll(other.gntFile_);
            }
            onChanged();
          }
        } else {
          if (!other.gntFile_.isEmpty()) {
            if (gntFileBuilder_.isEmpty()) {
              gntFileBuilder_.dispose();
              gntFileBuilder_ = null;
              gntFile_ = other.gntFile_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gntFileBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                  ? getGntFileFieldBuilder()
                  : null;
            } else {
              gntFileBuilder_.addAllMessages(other.gntFile_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        com.github.nicholasmoser.GNTFileProtos.GNTFiles parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.github.nicholasmoser.GNTFileProtos.GNTFiles) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTFile> gntFile_ =
          java.util.Collections.emptyList();

      private void ensureGntFileIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gntFile_ =
              new java.util.ArrayList<com.github.nicholasmoser.GNTFileProtos.GNTFile>(gntFile_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<com.github.nicholasmoser.GNTFileProtos.GNTFile, com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder, com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder> gntFileBuilder_;

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTFile> getGntFileList() {
        if (gntFileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gntFile_);
        } else {
          return gntFileBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public int getGntFileCount() {
        if (gntFileBuilder_ == null) {
          return gntFile_.size();
        } else {
          return gntFileBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTFile getGntFile(int index) {
        if (gntFileBuilder_ == null) {
          return gntFile_.get(index);
        } else {
          return gntFileBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder setGntFile(int index, com.github.nicholasmoser.GNTFileProtos.GNTFile value) {
        if (gntFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGntFileIsMutable();
          gntFile_.set(index, value);
          onChanged();
        } else {
          gntFileBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder setGntFile(int index,
          com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder builderForValue) {
        if (gntFileBuilder_ == null) {
          ensureGntFileIsMutable();
          gntFile_.set(index, builderForValue.build());
          onChanged();
        } else {
          gntFileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder addGntFile(com.github.nicholasmoser.GNTFileProtos.GNTFile value) {
        if (gntFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGntFileIsMutable();
          gntFile_.add(value);
          onChanged();
        } else {
          gntFileBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder addGntFile(int index, com.github.nicholasmoser.GNTFileProtos.GNTFile value) {
        if (gntFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGntFileIsMutable();
          gntFile_.add(index, value);
          onChanged();
        } else {
          gntFileBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder addGntFile(
          com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder builderForValue) {
        if (gntFileBuilder_ == null) {
          ensureGntFileIsMutable();
          gntFile_.add(builderForValue.build());
          onChanged();
        } else {
          gntFileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder addGntFile(int index,
          com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder builderForValue) {
        if (gntFileBuilder_ == null) {
          ensureGntFileIsMutable();
          gntFile_.add(index, builderForValue.build());
          onChanged();
        } else {
          gntFileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder addAllGntFile(
          java.lang.Iterable<? extends com.github.nicholasmoser.GNTFileProtos.GNTFile> values) {
        if (gntFileBuilder_ == null) {
          ensureGntFileIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, gntFile_);
          onChanged();
        } else {
          gntFileBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder clearGntFile() {
        if (gntFileBuilder_ == null) {
          gntFile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gntFileBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public Builder removeGntFile(int index) {
        if (gntFileBuilder_ == null) {
          ensureGntFileIsMutable();
          gntFile_.remove(index);
          onChanged();
        } else {
          gntFileBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder getGntFileBuilder(int index) {
        return getGntFileFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder getGntFileOrBuilder(
          int index) {
        if (gntFileBuilder_ == null) {
          return gntFile_.get(index);
        } else {
          return gntFileBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public java.util.List<? extends com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder> getGntFileOrBuilderList() {
        if (gntFileBuilder_ != null) {
          return gntFileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gntFile_);
        }
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder addGntFileBuilder() {
        return getGntFileFieldBuilder()
            .addBuilder(com.github.nicholasmoser.GNTFileProtos.GNTFile.getDefaultInstance());
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder addGntFileBuilder(int index) {
        return getGntFileFieldBuilder().addBuilder(index,
            com.github.nicholasmoser.GNTFileProtos.GNTFile.getDefaultInstance());
      }

      /**
       * <code>repeated .gntool.GNTFile gnt_file = 1;</code>
       */
      public java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder> getGntFileBuilderList() {
        return getGntFileFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<com.github.nicholasmoser.GNTFileProtos.GNTFile, com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder, com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder> getGntFileFieldBuilder() {
        if (gntFileBuilder_ == null) {
          gntFileBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<com.github.nicholasmoser.GNTFileProtos.GNTFile, com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder, com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder>(
                  gntFile_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
          gntFile_ = null;
        }
        return gntFileBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gntool.GNTFiles)
    }

    // @@protoc_insertion_point(class_scope:gntool.GNTFiles)
    private static final com.github.nicholasmoser.GNTFileProtos.GNTFiles DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.nicholasmoser.GNTFileProtos.GNTFiles();
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFiles getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GNTFiles> PARSER =
        new com.google.protobuf.AbstractParser<GNTFiles>() {
          @java.lang.Override
          public GNTFiles parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new GNTFiles(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<GNTFiles> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GNTFiles> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.nicholasmoser.GNTFileProtos.GNTFiles getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GNTFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gntool.GNTFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string file_path = 1;</code>
     */
    java.lang.String getFilePath();

    /**
     * <code>string file_path = 1;</code>
     */
    com.google.protobuf.ByteString getFilePathBytes();

    /**
     * <code>int32 hash = 2;</code>
     */
    int getHash();

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTChildFile> getGntChildFileList();

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    com.github.nicholasmoser.GNTFileProtos.GNTChildFile getGntChildFile(int index);

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    int getGntChildFileCount();

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    java.util.List<? extends com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder> getGntChildFileOrBuilderList();

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder getGntChildFileOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gntool.GNTFile}
   */
  public static final class GNTFile extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gntool.GNTFile)
      GNTFileOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use GNTFile.newBuilder() to construct.
    private GNTFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private GNTFile() {
      filePath_ = "";
      gntChildFile_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new GNTFile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private GNTFile(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            case 16: {

              hash_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gntChildFile_ =
                    new java.util.ArrayList<com.github.nicholasmoser.GNTFileProtos.GNTChildFile>();
                mutable_bitField0_ |= 0x00000001;
              }
              gntChildFile_.add(input.readMessage(
                  com.github.nicholasmoser.GNTFileProtos.GNTChildFile.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gntChildFile_ = java.util.Collections.unmodifiableList(gntChildFile_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(com.github.nicholasmoser.GNTFileProtos.GNTFile.class,
              com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder.class);
    }

    public static final int FILE_PATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object filePath_;

    /**
     * <code>string file_path = 1;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }

    /**
     * <code>string file_path = 1;</code>
     */
    public com.google.protobuf.ByteString getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASH_FIELD_NUMBER = 2;
    private int hash_;

    /**
     * <code>int32 hash = 2;</code>
     */
    public int getHash() {
      return hash_;
    }

    public static final int GNT_CHILD_FILE_FIELD_NUMBER = 3;
    private java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTChildFile> gntChildFile_;

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    public java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTChildFile> getGntChildFileList() {
      return gntChildFile_;
    }

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    public java.util.List<? extends com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder> getGntChildFileOrBuilderList() {
      return gntChildFile_;
    }

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    public int getGntChildFileCount() {
      return gntChildFile_.size();
    }

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    public com.github.nicholasmoser.GNTFileProtos.GNTChildFile getGntChildFile(int index) {
      return gntChildFile_.get(index);
    }

    /**
     * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
     */
    public com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder getGntChildFileOrBuilder(
        int index) {
      return gntChildFile_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filePath_);
      }
      if (hash_ != 0) {
        output.writeInt32(2, hash_);
      }
      for (int i = 0; i < gntChildFile_.size(); i++) {
        output.writeMessage(3, gntChildFile_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filePath_);
      }
      if (hash_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, hash_);
      }
      for (int i = 0; i < gntChildFile_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, gntChildFile_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.github.nicholasmoser.GNTFileProtos.GNTFile)) {
        return super.equals(obj);
      }
      com.github.nicholasmoser.GNTFileProtos.GNTFile other =
          (com.github.nicholasmoser.GNTFileProtos.GNTFile) obj;

      if (!getFilePath().equals(other.getFilePath()))
        return false;
      if (getHash() != other.getHash())
        return false;
      if (!getGntChildFileList().equals(other.getGntChildFileList()))
        return false;
      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash();
      if (getGntChildFileCount() > 0) {
        hash = (37 * hash) + GNT_CHILD_FILE_FIELD_NUMBER;
        hash = (53 * hash) + getGntChildFileList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.nicholasmoser.GNTFileProtos.GNTFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code gntool.GNTFile}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gntool.GNTFile)
        com.github.nicholasmoser.GNTFileProtos.GNTFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(com.github.nicholasmoser.GNTFileProtos.GNTFile.class,
                com.github.nicholasmoser.GNTFileProtos.GNTFile.Builder.class);
      }

      // Construct using com.github.nicholasmoser.GNTFileProtos.GNTFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getGntChildFileFieldBuilder();
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        filePath_ = "";

        hash_ = 0;

        if (gntChildFileBuilder_ == null) {
          gntChildFile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gntChildFileBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTFile_descriptor;
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTFile getDefaultInstanceForType() {
        return com.github.nicholasmoser.GNTFileProtos.GNTFile.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTFile build() {
        com.github.nicholasmoser.GNTFileProtos.GNTFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTFile buildPartial() {
        com.github.nicholasmoser.GNTFileProtos.GNTFile result =
            new com.github.nicholasmoser.GNTFileProtos.GNTFile(this);
        int from_bitField0_ = bitField0_;
        result.filePath_ = filePath_;
        result.hash_ = hash_;
        if (gntChildFileBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gntChildFile_ = java.util.Collections.unmodifiableList(gntChildFile_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gntChildFile_ = gntChildFile_;
        } else {
          result.gntChildFile_ = gntChildFileBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.nicholasmoser.GNTFileProtos.GNTFile) {
          return mergeFrom((com.github.nicholasmoser.GNTFileProtos.GNTFile) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.nicholasmoser.GNTFileProtos.GNTFile other) {
        if (other == com.github.nicholasmoser.GNTFileProtos.GNTFile.getDefaultInstance())
          return this;
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        if (other.getHash() != 0) {
          setHash(other.getHash());
        }
        if (gntChildFileBuilder_ == null) {
          if (!other.gntChildFile_.isEmpty()) {
            if (gntChildFile_.isEmpty()) {
              gntChildFile_ = other.gntChildFile_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGntChildFileIsMutable();
              gntChildFile_.addAll(other.gntChildFile_);
            }
            onChanged();
          }
        } else {
          if (!other.gntChildFile_.isEmpty()) {
            if (gntChildFileBuilder_.isEmpty()) {
              gntChildFileBuilder_.dispose();
              gntChildFileBuilder_ = null;
              gntChildFile_ = other.gntChildFile_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gntChildFileBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                  ? getGntChildFileFieldBuilder()
                  : null;
            } else {
              gntChildFileBuilder_.addAllMessages(other.gntChildFile_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        com.github.nicholasmoser.GNTFileProtos.GNTFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.nicholasmoser.GNTFileProtos.GNTFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object filePath_ = "";

      /**
       * <code>string file_path = 1;</code>
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string file_path = 1;</code>
       */
      public com.google.protobuf.ByteString getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string file_path = 1;</code>
       */
      public Builder setFilePath(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        filePath_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string file_path = 1;</code>
       */
      public Builder clearFilePath() {

        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }

      /**
       * <code>string file_path = 1;</code>
       */
      public Builder setFilePathBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        filePath_ = value;
        onChanged();
        return this;
      }

      private int hash_;

      /**
       * <code>int32 hash = 2;</code>
       */
      public int getHash() {
        return hash_;
      }

      /**
       * <code>int32 hash = 2;</code>
       */
      public Builder setHash(int value) {

        hash_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 hash = 2;</code>
       */
      public Builder clearHash() {

        hash_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTChildFile> gntChildFile_ =
          java.util.Collections.emptyList();

      private void ensureGntChildFileIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gntChildFile_ =
              new java.util.ArrayList<com.github.nicholasmoser.GNTFileProtos.GNTChildFile>(
                  gntChildFile_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<com.github.nicholasmoser.GNTFileProtos.GNTChildFile, com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder, com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder> gntChildFileBuilder_;

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTChildFile> getGntChildFileList() {
        if (gntChildFileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gntChildFile_);
        } else {
          return gntChildFileBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public int getGntChildFileCount() {
        if (gntChildFileBuilder_ == null) {
          return gntChildFile_.size();
        } else {
          return gntChildFileBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTChildFile getGntChildFile(int index) {
        if (gntChildFileBuilder_ == null) {
          return gntChildFile_.get(index);
        } else {
          return gntChildFileBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder setGntChildFile(int index,
          com.github.nicholasmoser.GNTFileProtos.GNTChildFile value) {
        if (gntChildFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGntChildFileIsMutable();
          gntChildFile_.set(index, value);
          onChanged();
        } else {
          gntChildFileBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder setGntChildFile(int index,
          com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder builderForValue) {
        if (gntChildFileBuilder_ == null) {
          ensureGntChildFileIsMutable();
          gntChildFile_.set(index, builderForValue.build());
          onChanged();
        } else {
          gntChildFileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder addGntChildFile(com.github.nicholasmoser.GNTFileProtos.GNTChildFile value) {
        if (gntChildFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGntChildFileIsMutable();
          gntChildFile_.add(value);
          onChanged();
        } else {
          gntChildFileBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder addGntChildFile(int index,
          com.github.nicholasmoser.GNTFileProtos.GNTChildFile value) {
        if (gntChildFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGntChildFileIsMutable();
          gntChildFile_.add(index, value);
          onChanged();
        } else {
          gntChildFileBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder addGntChildFile(
          com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder builderForValue) {
        if (gntChildFileBuilder_ == null) {
          ensureGntChildFileIsMutable();
          gntChildFile_.add(builderForValue.build());
          onChanged();
        } else {
          gntChildFileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder addGntChildFile(int index,
          com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder builderForValue) {
        if (gntChildFileBuilder_ == null) {
          ensureGntChildFileIsMutable();
          gntChildFile_.add(index, builderForValue.build());
          onChanged();
        } else {
          gntChildFileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder addAllGntChildFile(
          java.lang.Iterable<? extends com.github.nicholasmoser.GNTFileProtos.GNTChildFile> values) {
        if (gntChildFileBuilder_ == null) {
          ensureGntChildFileIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, gntChildFile_);
          onChanged();
        } else {
          gntChildFileBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder clearGntChildFile() {
        if (gntChildFileBuilder_ == null) {
          gntChildFile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gntChildFileBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public Builder removeGntChildFile(int index) {
        if (gntChildFileBuilder_ == null) {
          ensureGntChildFileIsMutable();
          gntChildFile_.remove(index);
          onChanged();
        } else {
          gntChildFileBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder getGntChildFileBuilder(
          int index) {
        return getGntChildFileFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder getGntChildFileOrBuilder(
          int index) {
        if (gntChildFileBuilder_ == null) {
          return gntChildFile_.get(index);
        } else {
          return gntChildFileBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public java.util.List<? extends com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder> getGntChildFileOrBuilderList() {
        if (gntChildFileBuilder_ != null) {
          return gntChildFileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gntChildFile_);
        }
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder addGntChildFileBuilder() {
        return getGntChildFileFieldBuilder()
            .addBuilder(com.github.nicholasmoser.GNTFileProtos.GNTChildFile.getDefaultInstance());
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder addGntChildFileBuilder(
          int index) {
        return getGntChildFileFieldBuilder().addBuilder(index,
            com.github.nicholasmoser.GNTFileProtos.GNTChildFile.getDefaultInstance());
      }

      /**
       * <code>repeated .gntool.GNTChildFile gnt_child_file = 3;</code>
       */
      public java.util.List<com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder> getGntChildFileBuilderList() {
        return getGntChildFileFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<com.github.nicholasmoser.GNTFileProtos.GNTChildFile, com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder, com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder> getGntChildFileFieldBuilder() {
        if (gntChildFileBuilder_ == null) {
          gntChildFileBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<com.github.nicholasmoser.GNTFileProtos.GNTChildFile, com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder, com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder>(
                  gntChildFile_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(),
                  isClean());
          gntChildFile_ = null;
        }
        return gntChildFileBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gntool.GNTFile)
    }

    // @@protoc_insertion_point(class_scope:gntool.GNTFile)
    private static final com.github.nicholasmoser.GNTFileProtos.GNTFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.nicholasmoser.GNTFileProtos.GNTFile();
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GNTFile> PARSER =
        new com.google.protobuf.AbstractParser<GNTFile>() {
          @java.lang.Override
          public GNTFile parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new GNTFile(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<GNTFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GNTFile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.nicholasmoser.GNTFileProtos.GNTFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GNTChildFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gntool.GNTChildFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string file_path = 1;</code>
     */
    java.lang.String getFilePath();

    /**
     * <code>string file_path = 1;</code>
     */
    com.google.protobuf.ByteString getFilePathBytes();

    /**
     * <code>int32 hash = 2;</code>
     */
    int getHash();

    /**
     * <code>bool compressed = 3;</code>
     */
    boolean getCompressed();

    /**
     * <code>string compressed_path = 4;</code>
     */
    java.lang.String getCompressedPath();

    /**
     * <code>string compressed_path = 4;</code>
     */
    com.google.protobuf.ByteString getCompressedPathBytes();
  }
  /**
   * Protobuf type {@code gntool.GNTChildFile}
   */
  public static final class GNTChildFile extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gntool.GNTChildFile)
      GNTChildFileOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use GNTChildFile.newBuilder() to construct.
    private GNTChildFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private GNTChildFile() {
      filePath_ = "";
      compressedPath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new GNTChildFile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private GNTChildFile(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            case 16: {

              hash_ = input.readInt32();
              break;
            }
            case 24: {

              compressed_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              compressedPath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTChildFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTChildFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.nicholasmoser.GNTFileProtos.GNTChildFile.class,
              com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder.class);
    }

    public static final int FILE_PATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object filePath_;

    /**
     * <code>string file_path = 1;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }

    /**
     * <code>string file_path = 1;</code>
     */
    public com.google.protobuf.ByteString getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASH_FIELD_NUMBER = 2;
    private int hash_;

    /**
     * <code>int32 hash = 2;</code>
     */
    public int getHash() {
      return hash_;
    }

    public static final int COMPRESSED_FIELD_NUMBER = 3;
    private boolean compressed_;

    /**
     * <code>bool compressed = 3;</code>
     */
    public boolean getCompressed() {
      return compressed_;
    }

    public static final int COMPRESSED_PATH_FIELD_NUMBER = 4;
    private volatile java.lang.Object compressedPath_;

    /**
     * <code>string compressed_path = 4;</code>
     */
    public java.lang.String getCompressedPath() {
      java.lang.Object ref = compressedPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        compressedPath_ = s;
        return s;
      }
    }

    /**
     * <code>string compressed_path = 4;</code>
     */
    public com.google.protobuf.ByteString getCompressedPathBytes() {
      java.lang.Object ref = compressedPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        compressedPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filePath_);
      }
      if (hash_ != 0) {
        output.writeInt32(2, hash_);
      }
      if (compressed_ != false) {
        output.writeBool(3, compressed_);
      }
      if (!getCompressedPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, compressedPath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filePath_);
      }
      if (hash_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, hash_);
      }
      if (compressed_ != false) {
        size += com.google.protobuf.CodedOutputStream.computeBoolSize(3, compressed_);
      }
      if (!getCompressedPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, compressedPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.github.nicholasmoser.GNTFileProtos.GNTChildFile)) {
        return super.equals(obj);
      }
      com.github.nicholasmoser.GNTFileProtos.GNTChildFile other =
          (com.github.nicholasmoser.GNTFileProtos.GNTChildFile) obj;

      if (!getFilePath().equals(other.getFilePath()))
        return false;
      if (getHash() != other.getHash())
        return false;
      if (getCompressed() != other.getCompressed())
        return false;
      if (!getCompressedPath().equals(other.getCompressedPath()))
        return false;
      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash();
      hash = (37 * hash) + COMPRESSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getCompressed());
      hash = (37 * hash) + COMPRESSED_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getCompressedPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.github.nicholasmoser.GNTFileProtos.GNTChildFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code gntool.GNTChildFile}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gntool.GNTChildFile)
        com.github.nicholasmoser.GNTFileProtos.GNTChildFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTChildFile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTChildFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.nicholasmoser.GNTFileProtos.GNTChildFile.class,
                com.github.nicholasmoser.GNTFileProtos.GNTChildFile.Builder.class);
      }

      // Construct using com.github.nicholasmoser.GNTFileProtos.GNTChildFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        filePath_ = "";

        hash_ = 0;

        compressed_ = false;

        compressedPath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.github.nicholasmoser.GNTFileProtos.internal_static_gntool_GNTChildFile_descriptor;
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTChildFile getDefaultInstanceForType() {
        return com.github.nicholasmoser.GNTFileProtos.GNTChildFile.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTChildFile build() {
        com.github.nicholasmoser.GNTFileProtos.GNTChildFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.nicholasmoser.GNTFileProtos.GNTChildFile buildPartial() {
        com.github.nicholasmoser.GNTFileProtos.GNTChildFile result =
            new com.github.nicholasmoser.GNTFileProtos.GNTChildFile(this);
        result.filePath_ = filePath_;
        result.hash_ = hash_;
        result.compressed_ = compressed_;
        result.compressedPath_ = compressedPath_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.nicholasmoser.GNTFileProtos.GNTChildFile) {
          return mergeFrom((com.github.nicholasmoser.GNTFileProtos.GNTChildFile) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.nicholasmoser.GNTFileProtos.GNTChildFile other) {
        if (other == com.github.nicholasmoser.GNTFileProtos.GNTChildFile.getDefaultInstance())
          return this;
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        if (other.getHash() != 0) {
          setHash(other.getHash());
        }
        if (other.getCompressed() != false) {
          setCompressed(other.getCompressed());
        }
        if (!other.getCompressedPath().isEmpty()) {
          compressedPath_ = other.compressedPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        com.github.nicholasmoser.GNTFileProtos.GNTChildFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.github.nicholasmoser.GNTFileProtos.GNTChildFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object filePath_ = "";

      /**
       * <code>string file_path = 1;</code>
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string file_path = 1;</code>
       */
      public com.google.protobuf.ByteString getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string file_path = 1;</code>
       */
      public Builder setFilePath(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        filePath_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string file_path = 1;</code>
       */
      public Builder clearFilePath() {

        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }

      /**
       * <code>string file_path = 1;</code>
       */
      public Builder setFilePathBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        filePath_ = value;
        onChanged();
        return this;
      }

      private int hash_;

      /**
       * <code>int32 hash = 2;</code>
       */
      public int getHash() {
        return hash_;
      }

      /**
       * <code>int32 hash = 2;</code>
       */
      public Builder setHash(int value) {

        hash_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 hash = 2;</code>
       */
      public Builder clearHash() {

        hash_ = 0;
        onChanged();
        return this;
      }

      private boolean compressed_;

      /**
       * <code>bool compressed = 3;</code>
       */
      public boolean getCompressed() {
        return compressed_;
      }

      /**
       * <code>bool compressed = 3;</code>
       */
      public Builder setCompressed(boolean value) {

        compressed_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bool compressed = 3;</code>
       */
      public Builder clearCompressed() {

        compressed_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object compressedPath_ = "";

      /**
       * <code>string compressed_path = 4;</code>
       */
      public java.lang.String getCompressedPath() {
        java.lang.Object ref = compressedPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          compressedPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string compressed_path = 4;</code>
       */
      public com.google.protobuf.ByteString getCompressedPathBytes() {
        java.lang.Object ref = compressedPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          compressedPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string compressed_path = 4;</code>
       */
      public Builder setCompressedPath(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        compressedPath_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string compressed_path = 4;</code>
       */
      public Builder clearCompressedPath() {

        compressedPath_ = getDefaultInstance().getCompressedPath();
        onChanged();
        return this;
      }

      /**
       * <code>string compressed_path = 4;</code>
       */
      public Builder setCompressedPathBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        compressedPath_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gntool.GNTChildFile)
    }

    // @@protoc_insertion_point(class_scope:gntool.GNTChildFile)
    private static final com.github.nicholasmoser.GNTFileProtos.GNTChildFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.nicholasmoser.GNTFileProtos.GNTChildFile();
    }

    public static com.github.nicholasmoser.GNTFileProtos.GNTChildFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GNTChildFile> PARSER =
        new com.google.protobuf.AbstractParser<GNTChildFile>() {
          @java.lang.Override
          public GNTChildFile parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new GNTChildFile(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<GNTChildFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GNTChildFile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.nicholasmoser.GNTFileProtos.GNTChildFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_gntool_GNTFiles_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gntool_GNTFiles_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_gntool_GNTFile_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gntool_GNTFile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_gntool_GNTChildFile_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gntool_GNTChildFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData =
        {"\n\013files.proto\022\006gntool\"-\n\010GNTFiles\022!\n\010gnt"
            + "_file\030\001 \003(\0132\017.gntool.GNTFile\"X\n\007GNTFile\022"
            + "\021\n\tfile_path\030\001 \001(\t\022\014\n\004hash\030\002 \001(\005\022,\n\016gnt_"
            + "child_file\030\003 \003(\0132\024.gntool.GNTChildFile\"\\"
            + "\n\014GNTChildFile\022\021\n\tfile_path\030\001 \001(\t\022\014\n\004has"
            + "h\030\002 \001(\005\022\022\n\ncompressed\030\003 \001(\010\022\027\n\017compresse"
            + "d_path\030\004 \001(\tB)\n\030com.github.nicholasmoser"
            + "B\rGNTFileProtosb\006proto3"};
    descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_gntool_GNTFiles_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_gntool_GNTFiles_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_gntool_GNTFiles_descriptor, new java.lang.String[] {"GntFile",});
    internal_static_gntool_GNTFile_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_gntool_GNTFile_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_gntool_GNTFile_descriptor,
            new java.lang.String[] {"FilePath", "Hash", "GntChildFile",});
    internal_static_gntool_GNTChildFile_descriptor = getDescriptor().getMessageTypes().get(2);
    internal_static_gntool_GNTChildFile_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_gntool_GNTChildFile_descriptor,
            new java.lang.String[] {"FilePath", "Hash", "Compressed", "CompressedPath",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
